### PR TITLE
Added chrome dev tools support

### PR DESCRIPTION
**Pull request by jckdrpr**
My knowledge of react and redux is a little rusty. Most probably I did not fuck something up :P. This adds support for `redux-dev-tools` chrome extension and falls back to a sidebar react component if the `dev-tools` are not present. I have found it to be quite helpful while debugging in the past. :)

P.S. These only affect the dev environment.

### CODE REVIEW

**Comment by Dremora** [comment]
Thanks a lot for the PR! Unfortunately, I've just realised I forgot to push two commits. One of them adds Dev Tools support, but without Chrome. Would you be able to rebase this PR to add Chrome Dev Tools support?

**Comment by Dremora** [comment]
Also, is there a way to reduce duplication between two `configureStore` functions? They are small enough for now but will likely grow in the future. I presume the reason for keeping them in two files is so that webpack can perform build-time optimization and exclude DevTools, is that correct?

**Comment by jckdrpr** [comment]
configureStore functions should not need to change from what I think, and yup webpack will perform build-time optimization and exclude DevTools from prod build.

**Comment by Dremora** [comment]
Sorry, haven't been really working on this project lately! But I'll merge the PR now, thanks!

**Pull request merged**
